### PR TITLE
[ADDED] PARTNER SECTION ADDED

### PR DESCRIPTION
**Pull request by Shivam-Fl**
### DESCRIPTION :
Added Partner Section
**FIXES** : FIXED ISSUE #7 

### CHECKLIST:

- [x]  Added partnerSection folder to the components folder in src
- [x]  Created index.jsx and data.js inside partnerSection folder
- [x] Created partnerSection folder in public directory and there added all the image and svg for partnerSection  
- [x]  Used flex and grids to set the layout of partner section
- [x]  Mapped data from data.js to partnerSection
- [x]  Installed inter font
- [x]  Created tailwind apply directives for partner's background gradient and main background in global.css folder
- [x]  Added  Inter font family and text color in tailwind.config.js
- [x]  Added Responsiveness to section

### FEATURES: 

- **DESKTOP VIEW**
 desktop view

- **DESKTOP VIEW [1440px]**
d-1440
d-14402

- **TABLET VIEW [768px]**
m-768
d-7682

- **MOBILE VIEW [320px]**
m-1
m-2

### CODE REVIEW

**Comment by kamalika0363** [comment]
LGTM!! @Shivam-Fl

**Review by yashodharpatel — CHANGES_REQUESTED** [review]
Images are in png format change them to svg
For the data dont create 2 seprate arrays just create one and then map it as anyways you are using grid
For the margin top above the 3rd item you can add the tailwind class that for third child there should be a margin top

**Comment by Shivam-Fl** [comment]
@yashodharpatel 

Two arrays as required as there is a difference in alignment of the boxes, two are at a height greater than two other

**Comment by Shivam-Fl** [comment]
@yashodharpatel changes done!

**Pull request merged**
